"""`runwall harden` -- the step that turns a tripwire into a lock.

Everything else in Runwall is enforcement *logic*. This is enforcement
*authority*, and without it the logic is advisory.

The problem it solves, stated plainly: by default the governor runs as the same
Windows principal as the agent it governs. Same-user process termination
requires no privilege at all. Any file the governor can write, the agent can
rewrite -- policy, manifest, ledger, client token, the hook registration. Process
self-protection against same-user kill is not achievable in userland; Protected
Process Light requires an ELAM/EV-signed driver. Path-based denylists lose to
junctions, hardlinks, 8.3 names, `\\\\?\\` prefixes and UNC-to-self.

So the only enforcement boundary actually available on this machine is a second
Windows principal. This module provisions one: a dedicated low-privilege local
account that owns the policy, the ledger and the keys, with ACLs that deny the
operator's own account write access to them.

**It generates a script rather than executing one.** Creating local accounts and
rewriting ACLs are privileged, hard-to-reverse changes to someone's machine. The
tool does the work of getting them right; the human pulls the trigger, having
read what it will do. `--apply` is offered, but the default is to write the
script and explain it.

What this still does not achieve, and must not be claimed: the operator is a
local administrator, so administrator-to-SYSTEM paths remain. The honest
statement is that this raises a bypass from an incidental single tool call to a
deliberate, multi-step, loudly-logged campaign against a boundary that leaves
evidence. That is a real and worthwhile change in posture. It is not
containment against a determined local administrator, and stronger isolation
means running the agent under a separate lower-privileged account or inside a VM.
"""
from __future__ import annotations

import os
import subprocess
import sys

from . import ROOT, STATE_DIR

SCRIPT_NAME = "runwall-harden.ps1"

TEMPLATE = r"""# Runwall hardening script
# Generated by `runwall harden`. Review before running.
# Run from an ELEVATED PowerShell prompt.
#
# What this does:
#   1. Creates a dedicated low-privilege local account for the governor.
#   2. Takes ownership of Runwall's enforcement surface with that account.
#   3. Denies your interactive account WRITE access to policy, keys and ledger,
#      while keeping READ so the console and hook still work.
#   4. Registers the governor as an auto-restarting Windows service under that
#      account, so crash-to-bypass costs the agent availability rather than
#      buying it permission.
#
# To reverse everything, run with -Undo.

param([switch]$Undo)

$ErrorActionPreference = "Stop"
$Account   = "{account}"
$RunwallRoot = "{root}"
$StateDir  = "{state}"
$Python    = "{python}"
$Me        = "$env:USERDOMAIN\$env:USERNAME"

if (-not ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)) {{
  Write-Error "This script must be run from an elevated PowerShell prompt."
  exit 1
}}

if ($Undo) {{
  Write-Host "Reverting Runwall hardening..." -ForegroundColor Yellow
  sc.exe stop RunwallGovernor 2>$null | Out-Null
  sc.exe delete RunwallGovernor 2>$null | Out-Null
  foreach ($p in @("$RunwallRoot\policy", "$RunwallRoot\runwall", "$RunwallRoot\hook", $StateDir)) {{
    if (Test-Path $p) {{ icacls $p /remove:d "$Me" /T /C | Out-Null }}
  }}
  if (Get-LocalUser -Name $Account -ErrorAction SilentlyContinue) {{
    Remove-LocalUser -Name $Account
  }}
  Write-Host "Reverted. Runwall is back to DETERRENCE + EVIDENCE posture." -ForegroundColor Green
  exit 0
}}

# --- 1. the governor's own principal ---------------------------------------
if (-not (Get-LocalUser -Name $Account -ErrorAction SilentlyContinue)) {{
  # A random password that is never displayed or stored: nothing ever needs to
  # log in as this account interactively, and a password nobody knows cannot be
  # phished, reused, or read out of a script.
  Add-Type -AssemblyName System.Web
  $pw = [System.Web.Security.Membership]::GeneratePassword(32, 8)
  $sec = ConvertTo-SecureString $pw -AsPlainText -Force
  New-LocalUser -Name $Account -Password $sec -PasswordNeverExpires `
    -AccountNeverExpires -UserMayNotChangePassword `
    -Description "Runwall governor service account" | Out-Null
  # Deliberately NOT added to Administrators or Users: this principal exists to
  # own files, not to have capability.
  Write-Host "Created local account $Account" -ForegroundColor Green
}} else {{
  Write-Host "Account $Account already exists" -ForegroundColor DarkGray
}}

# --- 2/3. ownership and ACLs ------------------------------------------------
# Enforcement surface: your account keeps READ (the console and hook need it)
# but loses WRITE. An agent running as you can no longer rewrite the policy it
# is judged by, the ledger that records it, or the keys that authenticate it.
foreach ($p in @("$RunwallRoot\policy", "$RunwallRoot\runwall", "$RunwallRoot\hook", $StateDir)) {{
  if (-not (Test-Path $p)) {{ continue }}
  icacls $p /grant "${{Account}}:(OI)(CI)F" /T /C | Out-Null
  icacls $p /deny  "${{Me}}:(OI)(CI)(W,D,DC,WDAC,WO)" /T /C | Out-Null
  Write-Host "ACL applied: $p" -ForegroundColor Green
}}

# The client token must stay readable by the agent's account -- the hook needs
# it to ask for decisions. That is safe by design: it can request a decision and
# nothing else. The approval key is a different matter.
icacls "$StateDir\client.token" /remove:d "$Me" /C | Out-Null
icacls "$StateDir\approval.key" /deny "${{Me}}:(R,W)" /C | Out-Null
icacls "$StateDir\operator.json" /deny "${{Me}}:(W)" /C | Out-Null
Write-Host "Split keys enforced: client token readable, approval key is not." -ForegroundColor Green

# --- 4. service, with auto-restart -----------------------------------------
$bin = "`"$Python`" -m runwall.cli up"
sc.exe create RunwallGovernor binPath= "$bin" start= auto obj= ".\$Account" `
  DisplayName= "Runwall Governor" 2>$null | Out-Null
# Restart on every failure: a crashed governor must cost the agent availability,
# never grant it permission.
sc.exe failure RunwallGovernor reset= 60 actions= restart/5000/restart/5000/restart/5000 | Out-Null
Write-Host "Service RunwallGovernor registered (auto-start, auto-restart)" -ForegroundColor Green

Write-Host ""
Write-Host "Hardening complete. Posture is now CONTAINMENT." -ForegroundColor Cyan
Write-Host "Set RUNWALL_HARDENED=1 in the service environment so the console reports it."
Write-Host ""
Write-Host "Still true after this step:" -ForegroundColor Yellow
Write-Host "  Your account remains a local administrator, so administrator-to-SYSTEM"
Write-Host "  paths still exist. This raises a bypass from one incidental tool call to a"
Write-Host "  deliberate, multi-step, logged campaign. It is not containment against a"
Write-Host "  determined local administrator. For that, run agents under a separate"
Write-Host "  lower-privileged account or inside a VM."
"""


def run_harden(args) -> int:
    from .term import init
    C, G = init()

    script = TEMPLATE.format(
        account=args.account,
        root=ROOT,
        state=STATE_DIR,
        python=sys.executable,
    )
    out_path = os.path.join(ROOT, SCRIPT_NAME)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"\n{C['bold']}Runwall hardening{C['reset']}")
    print(f"{C['dim']}{'-' * 74}{C['reset']}")
    print(f"Wrote {C['bold']}{out_path}{C['reset']}\n")
    print("It will:")
    for line in (
        f"create a low-privilege local account '{args.account}' with no group membership",
        "grant that account full control of policy/, runwall/, hook/ and .runwall/",
        "DENY your interactive account write access to those paths (read is kept)",
        "deny your account any access to approval.key, while leaving client.token readable",
        "register the governor as an auto-restarting Windows service under that account",
    ):
        print(f"  {G['dot']} {line}")

    print(f"\n{C['yellow']}This makes privileged, hard-to-reverse changes to your machine.{C['reset']}")
    print(f"Read it, then run from an {C['bold']}elevated{C['reset']} PowerShell prompt:\n")
    print(f"    powershell -ExecutionPolicy Bypass -File \"{out_path}\"\n")
    print(f"To reverse:\n\n    powershell -ExecutionPolicy Bypass -File \"{out_path}\" -Undo\n")

    print(f"{C['dim']}Why this step exists: until it runs, the governor and the agent are the")
    print(f"same Windows principal, so every defence is advisory -- anything the governor")
    print(f"can write, the agent can rewrite. A second principal is the only real")
    print(f"enforcement boundary available on this machine.{C['reset']}\n")
    print(f"{C['yellow']}Still true afterwards:{C['reset']} your account remains a local administrator,")
    print("so admin-to-SYSTEM paths remain. This raises a bypass from one incidental")
    print("tool call to a deliberate, multi-step, logged campaign. It is not containment")
    print("against a determined local administrator.\n")

    if not args.dry_run:
        print(f"{C['dim']}Re-run with --dry-run to only generate the script (this was the default "
              f"behaviour anyway: Runwall does not self-elevate).{C['reset']}")
    return 0
